name: Appium Test

on:
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-ios-app:
    runs-on: macos-13
    env:
      xcode-version: 14.3
      destination: name=iPhone 14
      demo-version: 1.6.3
    steps:
      - uses: actions/checkout@v3
        with:
          repository: saucelabs/my-demo-app-ios
          token: ${{ secrets.WDIO_ACCESS_TOKEN }}
          ref: ${{ env.demo-version }}
      - name: Install Dependencies
        run: gem install xcpretty
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.xcode-version }}
      - name: Set Release Version
        run: |
          xcrun agvtool new-marketing-version ${{ env.demo-version }}
      - name: Build for iOS Simulator
        run: |
          set -o pipefail && \
          xcodebuild \
            ONLY_ACTIVE_ARCH=NO \
            ARCHS_STANDARD="x86_64" \
            build \
            -workspace "My Demo App.xcworkspace" \
            -scheme "My Demo App" \
            -sdk iphonesimulator \
            -destination "${{ env.destination }}" \
            -configuration Release \
            -derivedDataPath build | xcpretty
      - name: Zip iOS Simulator Build
        run: |
          mkdir Payload
          cp -R build/Build/Products/Release-iphonesimulator/My\ Demo\ App.app Payload
          zip -r SauceLabs-Demo-App.Simulator.zip Payload
          rm -rf Payload
      - uses: actions/upload-artifact@v3
        with:
          name: SauceLabs-Demo-App.Simulator
          path: SauceLabs-Demo-App.Simulator.zip
          retention-days: 7
  run-on-ios:
    runs-on: macos-13
    needs: build-ios-app
    env:
      xcode-version: 14.3
      destination: iPhone 14
    steps:
    - uses: actions/checkout@v3
      with:
        repository: khoanhuynh-evizi/rc360-wdio
        token: ${{ secrets.WDIO_ACCESS_TOKEN }}
        ref: appium
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: yarn
    - uses: actions/download-artifact@v3
      with:
        name: SauceLabs-Demo-App.Simulator
        path: ./apps/SauceLabs-Demo-App.Simulator.zip
    - run: |
        chmod 777 /Users/runner/work/appium-actions/appium-actions/apps/SauceLabs-Demo-App.Simulator.zip
        unzip -o /Users/runner/work/appium-actions/appium-actions/apps/SauceLabs-Demo-App.Simulator.zip
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ env.xcode-version }}
    - uses: futureware-tech/simulator-action@v2
      with:
        model: ${{ env.destination }}
        erase_before_boot: true
        shutdown_after_job: true
    - run: yarn install --immutable
    - run: |
        npm install -g appium@2.0.0-rc.3
        appium driver install xcuitest
        appium driver install uiautomator2
    - name: Run webdriver-io tests
      uses: mathiasvr/command-output@v2.0.0
      id: wdio
      with:
        run: yarn ios:app
    - name: WDIO Test Checker
      run: | 
        cat > specs-reporter.log <<EOL
        ${{ steps.wdio.outputs.stdout }}
        EOL
        if [ !  -z "$(egrep '[0-9]+\sfailed,\s' specs-reporter.log)" ]; then
          exit 1
        fi
