name: Appium Test

on:
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  run-on-ios:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
      with:
        repository: khoanhuynh-evizi/rc360-wdio
        token: ${{ secrets.WDIO_ACCESS_TOKEN }}
        ref: appium
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: yarn
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - uses: futureware-tech/simulator-action@v2
      with:
        model: iPhone 14
        erase_before_boot: false
        shutdown_after_job: false
    - run: yarn install --frozen-lockfile
      id: wdio
    - run: |
        npm install -g appium@next
        appium plugin install execute-driver
        appium driver install xcuitest
        appium driver install uiautomator2
    - name: Run webdriver-io tests
      uses: mathiasvr/command-output@v2.0.0
      with:
        run: yarn ios:app
    - name: WDIO Test Checker
      run: | 
        cat > specs-reporter.log <<EOL
        ${{ steps.wdio.outputs.stdout }}
        EOL
        if [ !  -z "$(egrep '[0-9]+\sfailed,\s' specs-reporter.log)" ]; then
          exit 1
        fi
